name: Docker

on:
  push:
    branches:
      - main
    tags:
      - v*

env:
  IMAGE_NAME: answer
  DOCKER_HUB_USERNAME: woodchen
  DOCKER_HUB_REPO: answer

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        platform: [linux/amd64, linux/arm64]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build for ${{ matrix.platform }}
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile
          platforms: ${{ matrix.platform }}
          push: false
          load: false
          tags: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ matrix.platform }}-latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          outputs: type=docker,dest=/tmp/${{ matrix.platform }}.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.platform }}
          path: /tmp/${{ matrix.platform }}.tar

  push:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Download artifacts
        uses: actions/download-artifact@v3
        with:
          path: /tmp

      - name: Load images
        run: |
          docker load --input /tmp/linux-amd64/linux-amd64.tar
          docker load --input /tmp/linux-arm64/linux-arm64.tar

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.ACCESS_TOKEN }}

      - name: Push images
        run: |
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:linux-amd64-latest
          docker push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:linux-arm64-latest
          docker manifest create ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:linux-amd64-latest \
            ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:linux-arm64-latest
          docker manifest push ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest

  deploy:
    needs: push
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        env:
          DOCKER_IMAGE: ${{ env.DOCKER_HUB_USERNAME }}/${{ env.IMAGE_NAME }}
          PROJECT_PATH: ${{ secrets.PROJECT_PATH }}
        with:
          host: ${{ secrets.SERVER_IP }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          envs: DOCKER_IMAGE,PROJECT_PATH
          script: |
            docker pull $DOCKER_IMAGE:latest
            cd $PROJECT_PATH
            rm -rf ./i18n
            docker compose down
            docker compose up -d
